#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7yukc76PfGh3+5t9DFKlsgy...
      - lehrer key 
    ssh_pwauth: false
disable_root: true
package_update: true
package_upgrade: true
packages:
  - apache2
  - php
  - php-mysql
  - adminer
  - mysql-client
  - curl
  - wget
write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <head><title>Webserver</title></head>
      <body><h1>Webserver läuft!</h1></body>
      </html>
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>
  - path: /var/www/html/db.php
    content: |
      <?php
      $servername = "IP"; // Private IP des DB-Servers
      $username = "admin";
      $password = "Passwort";
      $dbname = "MainDatabase";

      $conn = new mysqli($servername, $username, $password, $dbname);

      if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
      }
      echo "Connected successfully";
      ?>
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
  - echo "Cloud-Init Web erfolgreich abgeschlossen" > /home/ubuntu/init.log